### ISSUE TITLE
Создание основного функционала

### ISSUE THREAD

**Issue by chicobambuni** [illdoodle/notes-project#1]
![image](https://github.com/illdoodle/notes-project/assets/166510108/330dbf07-4339-46ed-920a-a81c59e5a95d)
Создать интерфейс ориентируясь на дизайн-картинку.

Основной функционал приложения:
- вывод списка заметок
- добавление заметок
- удаление заметок
- маркировка заметок выполнено/не выполнено

Дополнительные требования к приложению:
- при добавлении заметка должна плавно появляться слева, двигая весь список вниз
- при удалении заметка должна плавно уходить вправо, двигая весь список вверх
- на одной странице должно быть не более 10-ти заметок, при превышении использовать пагинацию
- заметки должны сохраняться при перезагрузке страницы

**Comment by illdoodle** [comment]
основной функционал сделан
