### ISSUE TITLE
Правки в компоненте Notes

### ISSUE THREAD

**Issue by chicobambuni** [illdoodle/notes-project#8]
-  не использовать id в чистом виде, если компонент будет использован дважды на странице это приведёт к ошибке
- для статичных атрибутов чистого html не использовать {} т.к такая запись означает что атрибут будет проставлен reacto'м с помощью JS (`maxLength={50}` -> maxLength="50")
- в TSX (непосредственно return div...div) не использовать логику:
`onKeyDown={(e) => {e.code == 'Enter' ? addNote(document.querySelector('#notes-enter')) : true}}`
вынести в отдельную функцию
- избегать длинных однострочных записей, обеспечивать быструю читаемость кода
`setNotes([{id: 1, text: element.value.trim() ? element.value : newNotes.length + 1, completed: false}, ...newNotes]);`
```JS
setNotes([
  {
    id: 1,
    text: element.value.trim() ? element.value : newNotes.length + 1,
    completed: false
  },
  ...newNotes
]);
```
- для получения доступа к элемент #notes-enter использовать useRef (https://react.dev/learn/manipulating-the-dom-with-refs)
- если переназначение переменной не планируется использовать const, а не let
- избегать прямых манипуляций с DOM
`element.value = '';`, для контроля состояния DOM использовать useState
```JS
const [inputValue, setInutValue]= useState(null);
...
setInputValue('');
...
<input value={inputValue} ... />
```
- типизировать все структуры данных по аналогии:
![image](https://github.com/illdoodle/notes-project/assets/166510108/d314bd7a-89ab-4577-8340-5d67779fc3f4)
Необходимо для того что бы не собирать структуру по назначениям свойств в функциях, в этом прямое назначение TypeScript

**Comment by illdoodle** [comment]
Осталось разобраться с типизацией структур данных и отрефакторить id нотесов

> избегать прямых манипуляций с DOM

если задать input value={inputValue}, то в нем нельзя будет ничего напечатать
